# NO incluir 'version', ya no es necesario
services:
  postgres:
    image: postgres:15-alpine
    container_name: smarthealth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sm_admin
      POSTGRES_PASSWORD: sm2025
      POSTGRES_DB: smarthdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smarthealth_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sm_admin -d smarthdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smarthealth_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - ./.env
  
    ports:
      - "8088:8088"
    volumes:
      - ./src:/app/src
    networks:
      - smarthealth_network

networks:
  smarthealth_network:
    driver: bridge

volumes:
  postgres_data: